# Generated by Django 4.1.1 on 2022-10-06 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20221006_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_objetivo', models.BigIntegerField()),
                ('quantidade_atual', models.BigIntegerField()),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_limite', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('is_ativa', models.BooleanField()),
                ('is_cumprida', models.BooleanField()),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criador', to=settings.AUTH_USER_MODEL)),
                ('tipomidia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipomidia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
