# Generated by Django 4.1.1 on 2022-10-06 16:04

from django.db import migrations

def seed_tipos(apps, schema_editor):
    TipoMidia = apps.get_model('api', 'TipoMidia')
    tipos = ['Filme', 'Jogo', 'Livro']
    for tipo in tipos:
        tipo_midia = TipoMidia.objects.create(tipo=tipo)
        tipo_midia.save()  


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_tipos),
    ]
