# Generated by Django 4.1.1 on 2022-10-06 16:04

from django.db import migrations

def seed_types(apps, schema_editor):
    MediaType = apps.get_model('api', 'MediaType')
    types = ['Movie', 'Game', 'Book']
    for type in types:
        media_type = MediaType.objects.create(type=type)
        media_type.save()  


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_types),
    ]